apiVersion: v1
kind: Service
metadata:
  name: {{ template "memcached.fullname" . }}
  labels:
    app: {{ template "memcached.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    app: {{ template "memcached.name" . }}
